source 'https://github.com/shiguredo/sora-ios-sdk-specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'

target 'AppRTC' do
  use_frameworks!
  pod 'WebRTC', '86.4240.1.2'
  pod 'SocketRocket', '0.4.2'
end
